### ISSUE TITLE
Catholic schism mending and crusades

### ISSUE THREAD

**Issue by thefinestsieve** [Meneth/PB-git#174]
Currently mending the schism as a Catholic will prevent Catholics from calling further Crusades, which really doesn't make much sense. I already added a global flag called `cath_schism_mended` when I updated the schism mending event in PB, so all that needs to be done is a minor update to the Crusade CB.

**Comment by Meneth** [comment]
Yeah, that's not intended. Only the Orthodox mending the schism should stop crusades.

**Comment by thefinestsieve** [comment]
This issue can be closed now.
