### ISSUE TITLE
Religious authority and heresy problems

### ISSUE THREAD

**Issue by thefinestsieve** [Meneth/PB-git#195]
After collecting some firsthand experience in an ongoing multiplayer game with PB (yes, I know, it's shocking, but multiplayer works finally), I'm now opening an issue for this. In our game nothing unusually bad has happened to Catholicism. There's one antipope and they lost one crusade, but nevertheless about 1/6th of all Catholic provinces have already gone heretical by 1120; and it looks like heresy will completely take over within a century or so.

Convenient points:
- Reduction in MA has made heresy more common with all religions
- Due to the antipope authority malus, and the HRE/France nearly always setting up an antipope soon after the 1066 start, I've yet to see Catholic MA above 35 and more commonly it's in the 15-25 range; this means Catholicism is actually experiencing more heresy than many of the other religions
- The combination of reduced MA and PB's slower province religion conversions makes it devilishly difficult to counteract heretic provinces, which means more religious uprisings; if uprisings start to win battles, it can set off a feedback loop that effectively zeroes out the religion's MA, which appears to be the issue reported by one of our forumites; while this should be a possible outcome, right now it seems like it's happening too easily

**Comment by Meneth** [comment]
This was discussed in the chat at some point actually.
IIRC, the general ideas we lined out were:
Reducing the reduction of MA a bit.
Reducing the penalty for having an antipope from 30% to 25% or 20%

Combined this should hopefully rectify the issue, while still preventing Catholic MA from going as far overboard as it used to.

**Comment by thefinestsieve** [comment]
This can be closed.
