### ISSUE TITLE
Shattered balance events are firing upon startup

### ISSUE THREAD

**Issue by zijistark** [Meneth/PB-git#57]
SB events due to recent integration in beta are firing upon or after startup.  I can't easily test the crown authority law revocation cooldown implementation at the moment, because my branch is sitting at 1 past the beta's HEAD, and beta ain't playing nice.

It is apparently not disabling events about lucky rulers, immortals, etc. that have fired once at actual startup (all before I could touch the decisions menu or unpause) and, upon other attempts, within a few days of unpausing.

I don't currently know whether the other startup event modules are exhibiting similar behavior (did not have a chance to look for gender succession, e.g.).

**Comment by Meneth** [comment]
I've fixed a missing is_triggered_only now; that was probably what was causing it.

**Comment by zijistark** [comment]
All issues seem to be fixed.  Thanks.  Closing.
